/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Page extends javax.swing.JFrame {

    /**
     * Creates new form Page
     */
    public Page() {
        initComponents();
        setband();
    }
public void setband(){
    Selectband.list.add(new Selectband("Maroon5","M001","5000","100"));
    Selectband.ID.add("M001");
    Selectband.BAND.add("Maroon5");
    Selectband.PRICE.add("5000");
    Selectband.QTY.add("100");
    
    
    Selectband.list.add(new Selectband("Maroon5","M002","4000","100"));
    Selectband.ID.add("M002");
    Selectband.BAND.add("Maroon5");
    Selectband.PRICE.add("4000");
    Selectband.QTY.add("100");
    
    Selectband.list.add(new Selectband("Maroon5","M003","3000","100"));
    Selectband.ID.add("M003");
    Selectband.BAND.add("Maroon5");
    Selectband.PRICE.add("3000");
    Selectband.QTY.add("100");
    
    Selectband.list.add(new Selectband("Maroon5","M004","2500","100"));
    Selectband.ID.add("M004");
    Selectband.BAND.add("Maroon5");
    Selectband.PRICE.add("2500");
    Selectband.QTY.add("100");
    
    Selectband.list.add(new Selectband("Maroon5","M005","1500","100"));
    Selectband.ID.add("M005");
    Selectband.BAND.add("Maroon5");
    Selectband.PRICE.add("1500");
    Selectband.QTY.add("100");
    
    Selectband.list.add(new Selectband("Maroon5","M006","1000","100"));
    Selectband.ID.add("M006");
    Selectband.BAND.add("Maroon5");
    Selectband.PRICE.add("1000");
    Selectband.QTY.add("100");
    
    Selectband.list.add(new Selectband("5 Seconds Of Summer","S001","5000","100"));
    Selectband.ID.add("S001");
    Selectband.BAND.add("5 Seconds Of Summer");
    Selectband.PRICE.add("5000");
    Selectband.QTY.add("100");
    
    Selectband.list.add(new Selectband("5 Seconds Of Summer","S002","4000","100"));
    Selectband.ID.add("S002");
    Selectband.BAND.add("5 Seconds Of Summer");
    Selectband.PRICE.add("4000");
    Selectband.QTY.add("100");
    
    Selectband.list.add(new Selectband("5 Seconds Of Summer","S003","3000","100"));
    Selectband.ID.add("S003");
    Selectband.BAND.add("5 Seconds Of Summer");
    Selectband.PRICE.add("3000");
    Selectband.QTY.add("100");
    
    Selectband.list.add(new Selectband("5 Seconds Of Summer","S004","2500","100"));
    Selectband.ID.add("S004");
    Selectband.BAND.add("5 Seconds Of Summer");
    Selectband.PRICE.add("2500");
    Selectband.QTY.add("100");
    
    Selectband.list.add(new Selectband("5 Seconds Of Summer","S005","1500","100"));
    Selectband.ID.add("S005");
    Selectband.BAND.add("5 Seconds Of Summer");
    Selectband.PRICE.add("1500");
    Selectband.QTY.add("100");
    
    Selectband.list.add(new Selectband("5 Seconds Of Summer","S006","1000","100"));
    Selectband.ID.add("S006");
    Selectband.BAND.add("5 Seconds Of Summer");
    Selectband.PRICE.add("1000");
    Selectband.QTY.add("100");
    
    
    Selectband.list.add(new Selectband("The Vamps","V001","5000","100"));
    Selectband.ID.add("V001");
    Selectband.BAND.add("The Vamps");
    Selectband.PRICE.add("5000");
    Selectband.QTY.add("100");
    
    Selectband.list.add(new Selectband("The Vamps","V002","4000","100"));
    Selectband.ID.add("V002");
    Selectband.BAND.add("The Vamps");
    Selectband.PRICE.add("4000");
    Selectband.QTY.add("100");
    
    
    Selectband.list.add(new Selectband("The Vamps","V003","3000","100"));
    Selectband.ID.add("V003");
    Selectband.BAND.add("The Vamps");
    Selectband.PRICE.add("3000");
    Selectband.QTY.add("100");
    
    
    Selectband.list.add(new Selectband("The Vamps","V004","2500","100"));
    Selectband.ID.add("V004");
    Selectband.BAND.add("The Vamps");
    Selectband.PRICE.add("2500");
    Selectband.QTY.add("100");
    
    
    Selectband.list.add(new Selectband("The Vamps","V005","1500","100"));
    Selectband.ID.add("V005");
    Selectband.BAND.add("The Vamps");
    Selectband.PRICE.add("1500");
    Selectband.QTY.add("100");
    
    
    Selectband.list.add(new Selectband("The Vamps","V006","1000","100"));
    Selectband.ID.add("V006");
    Selectband.BAND.add("The Vamps");
    Selectband.PRICE.add("1000");
    Selectband.QTY.add("100");
    
    
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        Desk = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 650));
        setResizable(false);

        Desk.setPreferredSize(new java.awt.Dimension(1290, 900));

        javax.swing.GroupLayout DeskLayout = new javax.swing.GroupLayout(Desk);
        Desk.setLayout(DeskLayout);
        DeskLayout.setHorizontalGroup(
            DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
        );
        DeskLayout.setVerticalGroup(
            DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );

        jMenu1.setText("TICKET");

        jMenuItem1.setText("Maroon 5");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("5 Seconds Of Summer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("The Vamps");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("PRODUCT");

        jMenu3.setText("New Ticket");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem7.setText("Input Data Ticket");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem4.setText("Show Data Ticket");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenu2.add(jMenu3);

        jMenuItem5.setText("Update Band");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desk, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //ticket maroon 5
        Desk.removeAll();
        Desk.repaint();
        Ticket1 objtic = new Ticket1();
     
        Desk.add(objtic);
        objtic.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //ticket 5 seconds
        Desk.removeAll();
        Desk.repaint();
        Ticket2 objtic = new Ticket2();
     
        Desk.add(objtic);
        objtic.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //ticket the vamps
        Desk.removeAll();
        Desk.repaint();
        Ticket3 objtic = new Ticket3();
     
        Desk.add(objtic);
        objtic.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
         //newticket
        Desk.removeAll();
        Desk.repaint();
        Newticket objnewtic = new Newticket();
        
        Desk.add(objnewtic);
        objnewtic.show();
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Desk.removeAll();
        Desk.repaint();
        Updateband objup = new Updateband();
        
        Desk.add(objup);
        objup.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
 //newticket
        Desk.removeAll();
        Desk.repaint();
        Newticket objnewtic = new Newticket();
        
        Desk.add(objnewtic);
        objnewtic.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        //ผิด 
        Desk.removeAll();
         Desk.repaint();
         Showdata showdt = new Showdata();
         
         Desk.add(showdt);
         
         showdt.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desk;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
