/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Zone extends javax.swing.JInternalFrame {

    /**
     * Creates new form Zone1
     */
    public Zone() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        twothoufive = new javax.swing.JCheckBox();
        onethoufive = new javax.swing.JCheckBox();
        onethou = new javax.swing.JCheckBox();
        fivethou = new javax.swing.JCheckBox();
        fourthou = new javax.swing.JCheckBox();
        threethou = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        s4 = new javax.swing.JSpinner();
        s3 = new javax.swing.JSpinner();
        s25 = new javax.swing.JSpinner();
        s15 = new javax.swing.JSpinner();
        s1 = new javax.swing.JSpinner();
        s5 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        time = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("28 Days Later", 0, 50)); // NOI18N
        jLabel2.setText("Z O N E");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\kkkkkkkkkkk\\seating.gif")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Cordia New", 1, 36)); // NOI18N
        jLabel1.setText("REMARK");

        jLabel6.setText("ZONE");

        jLabel26.setText("ZONE");

        jLabel27.setText("ZONE");

        jLabel28.setText("ZONE");

        jLabel29.setText("ZONE");

        jLabel30.setText("ZONE");

        twothoufive.setText("2,500 BAHT");
        twothoufive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twothoufiveActionPerformed(evt);
            }
        });

        onethoufive.setText("1,500 BAHT");
        onethoufive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onethoufiveActionPerformed(evt);
            }
        });

        onethou.setText("1,000 BAHT");
        onethou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onethouActionPerformed(evt);
            }
        });

        fivethou.setText("5,000 BAHT");
        fivethou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivethouActionPerformed(evt);
            }
        });

        fourthou.setText("4,000 BAHT");
        fourthou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthouActionPerformed(evt);
            }
        });

        threethou.setText("3,000 BAHT");
        threethou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threethouActionPerformed(evt);
            }
        });

        jLabel12.setText("Seat :");

        jLabel13.setText("Seat :");

        jLabel14.setText("Seat :");

        jLabel15.setText("Seat :");

        jLabel16.setText("Seat :");

        jLabel17.setText("Seat :");

        s4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        s3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        s25.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        s15.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        s1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        s5.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        jLabel4.setFont(new java.awt.Font("Cordia New", 1, 36)); // NOI18N
        jLabel4.setText("TIME");

        jLabel25.setText("TIME :");

        time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sun 4  Dec 2016, 01.00 - 04.00 PM.", "Sun 4  Dec 2016, 06.00 - 09.00 PM.", " " }));
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });

        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sky.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orange.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pink.jpg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(10, 10, 10)
                                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(jLabel4))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(threethou)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(s3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fivethou)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(s5))
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(onethou)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fourthou)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(twothoufive)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(s25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(onethoufive)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(s15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(124, 124, 124))))
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jLabel2)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fivethou)
                                .addComponent(jLabel12)
                                .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fourthou, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(threethou, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(twothoufive)
                                .addComponent(jLabel15)
                                .addComponent(s25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(onethoufive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addComponent(s15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(onethou, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel25))
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void twothoufiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twothoufiveActionPerformed
        Selectband obj = new Selectband();
        if(twothoufive.isSelected())
        cal.Price=("2500");

        fivethou.setSelected(false);
        fourthou.setSelected(false);
        threethou.setSelected(false);
        onethoufive.setSelected(false);
        onethou.setSelected(false);

        s25.setEnabled(true);
        s5.setEnabled(false);
        s4.setEnabled(false);
        s3.setEnabled(false);
        s15.setEnabled(false);
        s1.setEnabled(false);
    }//GEN-LAST:event_twothoufiveActionPerformed

    private void onethoufiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onethoufiveActionPerformed
        Selectband obj = new Selectband();
        if(onethoufive.isSelected())
        cal.Price=("1500");

        fivethou.setSelected(false);
        fourthou.setSelected(false);
        threethou.setSelected(false);
        twothoufive.setSelected(false);
        onethou.setSelected(false);

        s15.setEnabled(true);
        s5.setEnabled(false);
        s4.setEnabled(false);
        s3.setEnabled(false);
        s25.setEnabled(false);
        s1.setEnabled(false);
    }//GEN-LAST:event_onethoufiveActionPerformed

    private void onethouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onethouActionPerformed
        Selectband obj = new Selectband();
        if(onethou.isSelected())
        cal.Price=("1000");

        fivethou.setSelected(false);
        fourthou.setSelected(false);
        threethou.setSelected(false);
        twothoufive.setSelected(false);
        onethoufive.setSelected(false);

        s1.setEnabled(true);{

        }

        s5.setEnabled(false);
        s4.setEnabled(false);
        s3.setEnabled(false);
        s25.setEnabled(false);
        s15.setEnabled(false);
    }//GEN-LAST:event_onethouActionPerformed

    private void fivethouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivethouActionPerformed
        Selectband obj = new Selectband();

        if(fivethou.isSelected())
        cal.Price="5000";

        fourthou.setSelected(false);
        threethou.setSelected(false);
        twothoufive.setSelected(false);
        onethoufive.setSelected(false);
        onethou.setSelected(false);

        s5.setEnabled(true);

        s4.setEnabled(false);
        s3.setEnabled(false);
        s25.setEnabled(false);
        s15.setEnabled(false);
        s1.setEnabled(false);
    }//GEN-LAST:event_fivethouActionPerformed

    private void fourthouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthouActionPerformed
        Selectband obj = new Selectband();

        if(fourthou.isSelected())
        cal.Price=("4000");

        fivethou.setSelected(false);
        threethou.setSelected(false);
        twothoufive.setSelected(false);
        onethoufive.setSelected(false);
        onethou.setSelected(false);

        s4.setEnabled(true);
        s5.setEnabled(false);
        s3.setEnabled(false);
        s25.setEnabled(false);
        s15.setEnabled(false);
        s1.setEnabled(false);
    }//GEN-LAST:event_fourthouActionPerformed

    private void threethouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threethouActionPerformed
        Selectband obj = new Selectband();
        if(threethou.isSelected())
        cal.Price=("3000");

        fivethou.setSelected(false);
        fourthou.setSelected(false);
        twothoufive.setSelected(false);
        onethoufive.setSelected(false);
        onethou.setSelected(false);

        s3.setEnabled(true);
        s5.setEnabled(false);
        s4.setEnabled(false);
        s25.setEnabled(false);
        s15.setEnabled(false);
        s1.setEnabled(false);
    }//GEN-LAST:event_threethouActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cal.Band="Maroon5";
        if(fivethou.isSelected()){
            cal.Seat=(Integer)s5.getValue();
        }
        else if(fourthou.isSelected()){
            cal.Seat=(Integer)s4.getValue();
        }
        else if(threethou.isSelected()){
            cal.Seat=(Integer)s3.getValue();
        }
        else if(twothoufive.isSelected()){
            cal.Seat=(Integer)s25.getValue();
        }
        else if(onethoufive.isSelected()){
            cal.Seat=(Integer)s15.getValue();
        }
        else if(onethou.isSelected()){
            cal.Seat=(Integer)s1.getValue();

        }
        cal.Band="5 Seconds Of Summer";
        if(fivethou.isSelected()){
            cal.Seat=(Integer)s5.getValue();
        }
        else if(fourthou.isSelected()){
            cal.Seat=(Integer)s4.getValue();
        }
        else if(threethou.isSelected()){
            cal.Seat=(Integer)s3.getValue();
        }
        else if(twothoufive.isSelected()){
            cal.Seat=(Integer)s25.getValue();
        }
        else if(onethoufive.isSelected()){
            cal.Seat=(Integer)s15.getValue();
        }
        else if(onethou.isSelected()){
            cal.Seat=(Integer)s1.getValue();

        }
        cal.Band="The Vamps";
        if(fivethou.isSelected()){
            cal.Seat=(Integer)s5.getValue();
        }
        else if(fourthou.isSelected()){
            cal.Seat=(Integer)s4.getValue();
        }
        else if(threethou.isSelected()){
            cal.Seat=(Integer)s3.getValue();
        }
        else if(twothoufive.isSelected()){
            cal.Seat=(Integer)s25.getValue();
        }
        else if(onethoufive.isSelected()){
            cal.Seat=(Integer)s15.getValue();
        }
        else if(onethou.isSelected()){
            cal.Seat=(Integer)s1.getValue();

        }
        cal.time= (String)time.getSelectedItem();
        Form form =new Form();
        this.getDesktopPane().add(form);
        form.setVisible(true);
        form.show();
        
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox fivethou;
    private javax.swing.JCheckBox fourthou;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox onethou;
    private javax.swing.JCheckBox onethoufive;
    private javax.swing.JSpinner s1;
    private javax.swing.JSpinner s15;
    private javax.swing.JSpinner s25;
    private javax.swing.JSpinner s3;
    private javax.swing.JSpinner s4;
    private javax.swing.JSpinner s5;
    private javax.swing.JCheckBox threethou;
    private javax.swing.JComboBox<String> time;
    private javax.swing.JCheckBox twothoufive;
    // End of variables declaration//GEN-END:variables
}
